### ISSUE TITLE
Submodules not being included

### ISSUE THREAD

**Issue by sharpninja** [PoshCode/Pansies#16]
> Note: I'm including ColorMine and p2f as submodules, you may need to update them with:
>
> ```posh
> git submodule update --init -recursive
> ```

This does not work.  PowerShell 7, Windows 10 2004, git version 2.27.0.windows.1

**Comment by Jaykul** [comment]
It's supposed to be:
```
git submodule update --init --recursive
```
However, you shouldn't need to do that _unless the submodules change_ if you cloned it with `--recursive`
