### ISSUE TITLE
Pansies Works In Powershell But Not ISE

### ISSUE THREAD

**Issue by GitDaan** [PoshCode/Pansies#4]
Pansies works in Powershell 5.1 - With all the business tasks and daily stress, it is kind of fun to have this whimsy around. However, it is not working in the ISE which is really all we use these days (long live POPS).

**Comment by MartinSGill** [comment]
I doubt it will ever work. The ISE host does not support ANSI escape sequences and Microsoft is no longer supporting ISE, having retired it.

**Comment by Jaykul** [comment]
Nope. Sorry. There's no support there for the **ANSI** <strong>E</strong>scape <strong>S</strong>equences part of **PANSIES** 😉

They _could_ have implemented escape sequences (PoshConsole did, before ISE even existed), but they didn't, and now it's abandonware. As far as I'm concerned, it's dead.
