### ISSUE TITLE
Unable To Download Module From PowershellGallery 

### ISSUE THREAD

**Issue by thedwindlingdba** [PoshCode/Pansies#7]
Hello,

When attempting to install the Pansies module from the powershell gallery using the following syntax 
Find-Module -Name "Pansies" -IncludeDependencies | Install-Module -Force -AllowClobber -Verbose 

I receive the following error (I have also attached a screenshot of said error):
PackageManagement\Install-Package : The module 'Pansies' cannot be installed
or updated because it is not a properly-formed module.
At C:\Program
Files\WindowsPowerShell\Modules\PowerShellGet\1.5.0.0\PSModule.psm1:1980
char:34
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPac
   kage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : InvalidManifestModule,Test-ValidManifestModule,M
   icrosoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
![image](https://user-images.githubusercontent.com/26493075/32461350-1c85cef6-c2fb-11e7-90a4-7ac83a117586.png)

**Comment by scrthq** [comment]
Same here when trying to install on a new machine, causes the newest version of PowerLine to fail because it can't load Pansies as a dependancy

**Comment by Jaykul** [comment]
If you're trying to install a version over the top of the same version that's already imported, you would have trouble, because the module includes a binary assembly that would be locked in memory.

The current `prerelease` version works. Can you try that?

```posh
Install-Module Pansies -Scope Currentuser -AllowPrerelease -AllowClobber
```
